### ISSUE TITLE
Service https://docker-hub-rss.ezhub.de/ is not working currently

### ISSUE THREAD

**Issue by wojciech-kopras** [markhaehnel/docker-hub-rss#5]
It seems that service https://docker-hub-rss.ezhub.de/ is not working currently. Will it be up again?

```
$ curl 'https://docker-hub-rss.ezhub.de/'                                                 
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to docker-hub-rss.ezhub.de:443
```

**Comment by markhaehnel** [comment]
Unfortunately, I have no capacity to keep the service running.
But you can easily self-host it!

**Comment by dlehammer** [comment]
Hi @markhaehnel,

Consider updating the README to reflect:
> Unfortunately, I have no capacity to keep the service running.

To avoid further duplicate issues reported :)

**Comment by markhaehnel** [comment]
Just did it, thank you for pointing out!
